---
- hosts: webserver
  gather_facts: True
  user: ec2-user
  become: yes
  tasks:

    # fetch instance data from the metadata servers in ec2
    - ec2_facts:

    # just show the instance-id
    - debug: msg="{{ hostvars[inventory_hostname]['ansible_ec2_instance_id'] }}"

- hosts: delete
  gather_facts: True
  connection: local
  vars:
    region: "us-east-2"
  tasks:
    - name: Terminate instances
      ec2: state='absent'
           region={{ region }}
           instance_ids={{ item }}
           wait=true
      with_items: "{{ hostvars[inventory_hostname]['ansible_ec2_instance_id'] }}"
